name: Android CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease


      - name: Check Android Build Tools
        run: |
          ls /usr/local/lib/android/sdk/build-tools/

      - name: Sign Release
        id: sign_app
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Move artifact
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-signed.apk

      - name: Generate changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "## Коммиты с прошлого релиза $LAST_TAG" > CHANGELOG.md
          git log $LAST_TAG..HEAD --oneline >> CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: app/build/outputs/apk/release/app-release-signed.apk
          bodyFile: CHANGELOG.md